name: External Cron

on:
  schedule:
    - cron: "0,30 * * * *"   # la fix și la și jumate
  workflow_dispatch:

jobs:
  call-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Call website cron
        run: |
          curl -L \
          -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36" \
          "https://stiri.ct.ws/generate_feed.php?key=38022088108365"
